{
 "title": "AetherLogic - Nodes Dashboard",
 "tags": [
  "aetherlogic",
  "iot",
  "air-quality",
  "industrial"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "NodeID",
    "label": "Select Node",
    "query": {
     "query": "from(bucket: \"eap_plh40\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\r\n  |> keep(columns: [\"id\"])\r\n  |> distinct(column: \"id\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Measurements per Node (Analysis: Current/Avg/Max/Min)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Temperature Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"temp\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "Humidity Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"hum\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "Noise Analysis (dB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"db\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\" // Εισαγωγή βιβλιοθήκης για στρογγυλοποίηση\r\n\r\nfrom(bucket: \"eap_plh40\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"${NodeID}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"v\")\r\n  |> last()\r\n  |> map(fn: (r) => {\r\n      // 1. Υπολογισμός Ποσοστού\r\n      pct = if r._value >= 4.1 then 100.0\r\n            else if r._value <= 3.0 then 0.0\r\n            else (r._value - 3.0) / 1.1 * 100.0\r\n\r\n      // 2. Στρογγυλοποίηση Volt σε 2 δεκαδικά (π.χ. 3.45)\r\n      volts = math.round(x: r._value * 100.0) / 100.0\r\n\r\n      // 3. Επιστροφή: Τιμή = Ποσοστό, Όνομα = \"3.45 V\"\r\n      return {\r\n          _time: r._time,\r\n          _value: pct,\r\n          _field: string(v: volts) + \" V\"\r\n      }\r\n  })"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"eap_plh40\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"${NodeID}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Packages / Lost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"eap_plh40\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"${NodeID}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pkt\")\r\n  // ΣΗΜΑΝΤΙΚΟ: Μετατροπή σε ακέραιο (int) για αποφυγή προβλημάτων τύπου\r\n  |> map(fn: (r) => ({ r with _value: int(v: r._value) }))\r\n  |> group(columns: [\"topic\"]) \r\n  \r\n  // Υπολογίζουμε min, max, count σε ένα πέρασμα\r\n  |> reduce(\r\n      identity: {count: 0, min: 0, max: 0, first: true},\r\n      fn: (r, accumulator) => ({\r\n        count: accumulator.count + 1,\r\n        min: if accumulator.first then r._value else (if r._value < accumulator.min then r._value else accumulator.min),\r\n        max: if accumulator.first then r._value else (if r._value > accumulator.max then r._value else accumulator.max),\r\n        first: false\r\n      })\r\n  )\r\n  \r\n  // Κάνουμε τα μαθηματικά: Expected - Actual = Lost\r\n  |> map(fn: (r) => {\r\n      expected = r.max - r.min + 1\r\n      lost = expected - r.count\r\n      return {\r\n        node: r.topic, \r\n        latest_seq: r.max, \r\n        total_lost: lost,\r\n        // Υπολογισμός ποσοστού: (Lost / Expected) * 100\r\n        loss_perc: if expected > 0 then (float(v: lost) / float(v: expected)) * 100.0 else 0.0\r\n      }\r\n  })\r\n  \r\n  |> drop(columns: [\"min\", \"max\", \"count\", \"first\"])"
    }
   ]
  },
  {
   "title": "PM 1.0 Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"pm1\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "PM 2.5 Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"pm25\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "PM 10 Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"pm10\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "VOC Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"tvoc\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "CO2 Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"co2\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "IAQ Analysis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nbase = from(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"iaq\") |> group(columns: [\"id\"])\r\nmi = base |> min() |> map(fn: (r) => ({ r with _field: \"Min\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nma = base |> max() |> map(fn: (r) => ({ r with _field: \"Max\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nav = base |> mean() |> map(fn: (r) => ({ r with _field: \"Avg\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\ncu = base |> last() |> map(fn: (r) => ({ r with _field: \"Now\" })) |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"gw\", \"host\", \"topic\", \"node\"])\r\nunion(tables: [cu, av, ma, mi]) |> group()"
    }
   ]
  },
  {
   "title": "Time Series (Comparative Charts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Temperature Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nfrom(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"temp\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "Humidity Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nfrom(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"hum\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "Noise Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nfrom(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"db\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "PM 1.0 Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nfrom(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"pm1\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "PM 2.5 Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nfrom(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"pm25\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "PM 10.0 Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nfrom(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"pm10\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "CO2 Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"eap_plh40\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"co2\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "VOC Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "targets": [
    {
     "query": "from(bucket: \"eap_plh40\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"tvoc\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "IAQ Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"eap_plh40\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"iaq\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  },
  {
   "title": "Battery Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "rangeDuration = uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)\r\nrangeHours = float(v: rangeDuration) / 1000000000.0 / 3600.0\r\nsBucket = if rangeHours > 168.0 then \"eap_plh40_1d\" else if rangeHours > 48.0 then \"eap_plh40_1h\" else \"eap_plh40\"\r\nfrom(bucket: sBucket) |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"air_quality\") |> filter(fn: (r) => r.id == \"${NodeID}\") |> filter(fn: (r) => r._field == \"v\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> drop(columns: [\"gw\", \"host\", \"topic\", \"node\"]) |> map(fn: (r) => ({ r with _field: \"Node \" + r.id }))"
    }
   ]
  }
 ]
}